name: Publish ASIST

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-vsce'

jobs:
  check-tag:
    runs-on: ubuntu-latest
    outputs:
      publish_binary: ${{ steps.set-vars.outputs.publish_binary }}
      publish_extension: ${{ steps.set-vars.outputs.publish_extension }}
      tag_number: ${{ steps.set-vars.outputs.tag_number }}

    steps:
      - name: Set output variables based on tag
        id: set-vars
        run: |
          TAG="${GITHUB_REF##*/}"
          echo "Tag is: $TAG"

          if [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Extension and Binary release"
            echo "publish_binary=true" >> $GITHUB_OUTPUT
            echo "publish_extension=true" >> $GITHUB_OUTPUT
          elif [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-vsce$ ]]; then
            echo "Only extension release"
            echo "publish_binary=false" >> $GITHUB_OUTPUT
            echo "publish_extension=true" >> $GITHUB_OUTPUT
          else
            echo "Tag format not recognized"
            exit 1
          fi

          echo "tag_number=$TAG" >> $GITHUB_OUTPUT

  release-binary:
    if: ${{ needs.check-tag.outputs.publish_binary == 'true' }}
    needs: check-tag
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.check-tag.outputs.tag_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Build Binaries
        run: make build-binaries

  publish-extension:
    if: >
      always() &&
      needs.check-tag.outputs.publish_extension == 'true' &&
      (
        needs.release-binary.result == 'success' ||
        (needs.check-tag.outputs.publish_binary == 'false' && needs.release-binary.result == 'skipped')
      )
    needs: [check-tag, release-binary]
    runs-on: ubuntu-latest
    steps:
      - name: Strip leading 'v' from tag
        run: |
          TAG="${{ needs.check-tag.outputs.tag_number }}"
          if [[ "$TAG" == v* ]]; then
            VERSION="${TAG:1}" # remove first character i.e. v
          else
            VERSION="$TAG"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'
          
      - name: Build Binaries
        run: make build-binaries

      - name: Copy binary into extension
        run: |
          cp ./asist.exe ./extension/asist.exe
          cp ./asist_darwin_amd64 ./extension/asist_darwin_amd64
          cp ./asist_darwin_arm64 ./extension/asist_darwin_arm64
          cp ./asist_linux_amd64 ./extension/asist_linux_amd64
          cp ./asist_linux_arm64 ./extension/asist_linux_arm64

      - name: Build vsix package
        run: make build-vscode-extension-binary-exist

      - name: Publish to VS Code Marketplace and Open VSX
        run: |
          cd extension
          echo "Verify vsce token has not expired"
          echo "Publish to vsce"
          ls .